// Code generated by ent, DO NOT EDIT.

package tables_type

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tables_type type in the database.
	Label = "tables_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTablesID holds the string denoting the tables_id field in the database.
	FieldTablesID = "tables_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the tables_type in the database.
	Table = "tables_types"
)

// Columns holds all SQL columns for tables_type fields.
var Columns = []string{
	FieldID,
	FieldTablesID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Tables_type queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTablesID orders the results by the tables_id field.
func ByTablesID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTablesID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}
