// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cafe-management/ent/qrcode"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// QrCode is the model entity for the QrCode schema.
type QrCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Image holds the value of the "image" field.
	Image        string `json:"image,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QrCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case qrcode.FieldID:
			values[i] = new(sql.NullInt64)
		case qrcode.FieldURL, qrcode.FieldImage:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QrCode fields.
func (qc *QrCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case qrcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			qc.ID = int(value.Int64)
		case qrcode.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				qc.URL = value.String
			}
		case qrcode.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				qc.Image = value.String
			}
		default:
			qc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QrCode.
// This includes values selected through modifiers, order, etc.
func (qc *QrCode) Value(name string) (ent.Value, error) {
	return qc.selectValues.Get(name)
}

// Update returns a builder for updating this QrCode.
// Note that you need to call QrCode.Unwrap() before calling this method if this QrCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (qc *QrCode) Update() *QrCodeUpdateOne {
	return NewQrCodeClient(qc.config).UpdateOne(qc)
}

// Unwrap unwraps the QrCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (qc *QrCode) Unwrap() *QrCode {
	_tx, ok := qc.config.driver.(*txDriver)
	if !ok {
		panic("ent: QrCode is not a transactional entity")
	}
	qc.config.driver = _tx.drv
	return qc
}

// String implements the fmt.Stringer.
func (qc *QrCode) String() string {
	var builder strings.Builder
	builder.WriteString("QrCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", qc.ID))
	builder.WriteString("url=")
	builder.WriteString(qc.URL)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(qc.Image)
	builder.WriteByte(')')
	return builder.String()
}

// QrCodes is a parsable slice of QrCode.
type QrCodes []*QrCode
