// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cafe-management/ent/schema"
	"cafe-management/ent/tables"
	"cafe-management/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tablesFields := schema.Tables{}.Fields()
	_ = tablesFields
	// tablesDescCreatedAt is the schema descriptor for created_at field.
	tablesDescCreatedAt := tablesFields[4].Descriptor()
	// tables.DefaultCreatedAt holds the default value on creation for the created_at field.
	tables.DefaultCreatedAt = tablesDescCreatedAt.Default.(time.Time)
	// tablesDescUpdatedAt is the schema descriptor for updated_at field.
	tablesDescUpdatedAt := tablesFields[5].Descriptor()
	// tables.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tables.DefaultUpdatedAt = tablesDescUpdatedAt.Default.(time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(time.Time)
}
