// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cafe-management/ent/tables_type"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TablesTypeCreate is the builder for creating a Tables_type entity.
type TablesTypeCreate struct {
	config
	mutation *TablesTypeMutation
	hooks    []Hook
}

// SetTablesID sets the "tables_id" field.
func (ttc *TablesTypeCreate) SetTablesID(i int) *TablesTypeCreate {
	ttc.mutation.SetTablesID(i)
	return ttc
}

// SetName sets the "name" field.
func (ttc *TablesTypeCreate) SetName(s string) *TablesTypeCreate {
	ttc.mutation.SetName(s)
	return ttc
}

// Mutation returns the TablesTypeMutation object of the builder.
func (ttc *TablesTypeCreate) Mutation() *TablesTypeMutation {
	return ttc.mutation
}

// Save creates the Tables_type in the database.
func (ttc *TablesTypeCreate) Save(ctx context.Context) (*Tables_type, error) {
	return withHooks(ctx, ttc.sqlSave, ttc.mutation, ttc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ttc *TablesTypeCreate) SaveX(ctx context.Context) *Tables_type {
	v, err := ttc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttc *TablesTypeCreate) Exec(ctx context.Context) error {
	_, err := ttc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttc *TablesTypeCreate) ExecX(ctx context.Context) {
	if err := ttc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ttc *TablesTypeCreate) check() error {
	if _, ok := ttc.mutation.TablesID(); !ok {
		return &ValidationError{Name: "tables_id", err: errors.New(`ent: missing required field "Tables_type.tables_id"`)}
	}
	if _, ok := ttc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tables_type.name"`)}
	}
	return nil
}

func (ttc *TablesTypeCreate) sqlSave(ctx context.Context) (*Tables_type, error) {
	if err := ttc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ttc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ttc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ttc.mutation.id = &_node.ID
	ttc.mutation.done = true
	return _node, nil
}

func (ttc *TablesTypeCreate) createSpec() (*Tables_type, *sqlgraph.CreateSpec) {
	var (
		_node = &Tables_type{config: ttc.config}
		_spec = sqlgraph.NewCreateSpec(tables_type.Table, sqlgraph.NewFieldSpec(tables_type.FieldID, field.TypeInt))
	)
	if value, ok := ttc.mutation.TablesID(); ok {
		_spec.SetField(tables_type.FieldTablesID, field.TypeInt, value)
		_node.TablesID = value
	}
	if value, ok := ttc.mutation.Name(); ok {
		_spec.SetField(tables_type.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// TablesTypeCreateBulk is the builder for creating many Tables_type entities in bulk.
type TablesTypeCreateBulk struct {
	config
	err      error
	builders []*TablesTypeCreate
}

// Save creates the Tables_type entities in the database.
func (ttcb *TablesTypeCreateBulk) Save(ctx context.Context) ([]*Tables_type, error) {
	if ttcb.err != nil {
		return nil, ttcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ttcb.builders))
	nodes := make([]*Tables_type, len(ttcb.builders))
	mutators := make([]Mutator, len(ttcb.builders))
	for i := range ttcb.builders {
		func(i int, root context.Context) {
			builder := ttcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TablesTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ttcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ttcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ttcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ttcb *TablesTypeCreateBulk) SaveX(ctx context.Context) []*Tables_type {
	v, err := ttcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttcb *TablesTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := ttcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttcb *TablesTypeCreateBulk) ExecX(ctx context.Context) {
	if err := ttcb.Exec(ctx); err != nil {
		panic(err)
	}
}
