// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Price is the predicate function for price builders.
type Price func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Reservation is the predicate function for reservation builders.
type Reservation func(*sql.Selector)

// Tables is the predicate function for tables builders.
type Tables func(*sql.Selector)

// Tables_type is the predicate function for tables_type builders.
type Tables_type func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
